---

- name: "Update local apt repo"
  become: true
  apt:
    update_cache: yes
    
- name: "Update apt packages"
  become: true
  apt:
    upgrade: yes
    
- name: "Remove stale dependencies"
  become: true
  apt:
    autoremove: yes
    
- name: "Install dependencies [nodejs and npm]"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
   
  # pm = process manager 
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest
    
- name: "Creates backend app directory"
  become: true
  file:
    path: ~/backend-app
    state: directory
    
- name: "Unarchive backend files"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app
    
- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i
    
- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"
    
- name: "Configure pm2 to start as service"
  become: true
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
